import { GLTF } from 'three-stdlib';
import * as THREE from 'three';

export type GLTFResult = GLTF & {
  nodes: {
    墙体: THREE.Mesh;
    书桌: THREE.Mesh;
    手机_1: THREE.Mesh;
    手机_2: THREE.Mesh;
    桌腿: THREE.Mesh;
    电脑_1: THREE.Mesh;
    电脑_2: THREE.Mesh;
    电脑屏幕: THREE.Mesh;
    触控板_1: THREE.Mesh;
    触控板_2: THREE.Mesh;
    键盘: THREE.Mesh;
    _键帽: THREE.Mesh;
    平板_1: THREE.Mesh;
    平板_2: THREE.Mesh;
    柜子: THREE.Mesh;
    书架: THREE.Mesh;
    手办: THREE.Mesh;
    日历: THREE.Mesh;
    文本: THREE.Mesh;
    _留言板: THREE.Mesh;
    _留言板_1: THREE.Mesh;
    贴纸: THREE.Mesh;
    贴纸001: THREE.Mesh;
    贴纸002: THREE.Mesh;
    贴纸003: THREE.Mesh;
    CD机: THREE.Mesh;
    CD拉绳: THREE.Mesh;
    唱片: THREE.Mesh;
    地毯_1: THREE.Mesh;
    地毯_2: THREE.Mesh;
    椅子: THREE.Mesh;
    头: THREE.Mesh;
    小臂: THREE.Mesh;
    大臂: THREE.Mesh;
    脚: THREE.Mesh;
    小腿: THREE.Mesh;
    大腿: THREE.Mesh;
    身子: THREE.Mesh;
    沙发: THREE.Mesh;
    头001: THREE.Mesh;
    小臂001: THREE.Mesh;
    大臂001: THREE.Mesh;
    脚001: THREE.Mesh;
    小腿001: THREE.Mesh;
    大腿001: THREE.Mesh;
    身子001: THREE.Mesh;
    骨骼: THREE.Bone;
    骨骼_1: THREE.Bone;
  };
  materials: {
    墙体: THREE.MeshStandardMaterial;
    书桌: THREE.MeshStandardMaterial;
    手机: THREE.MeshStandardMaterial;
    手机屏保: THREE.MeshStandardMaterial;
    桌腿: THREE.MeshStandardMaterial;
    电脑: THREE.MeshStandardMaterial;
    电脑屏幕: THREE.MeshStandardMaterial;
    电脑屏保: THREE.MeshStandardMaterial;
    触控板: THREE.MeshStandardMaterial;
    触控板玻璃: THREE.MeshStandardMaterial;
    键盘: THREE.MeshStandardMaterial;
    键帽: THREE.MeshStandardMaterial;
    平板: THREE.MeshStandardMaterial;
    平板屏幕: THREE.MeshStandardMaterial;
    柜子: THREE.MeshStandardMaterial;
    书架: THREE.MeshStandardMaterial;
    手办: THREE.MeshStandardMaterial;
    日历: THREE.MeshStandardMaterial;
    标题: THREE.MeshStandardMaterial;
    留言板: THREE.MeshStandardMaterial;
    便利贴: THREE.MeshStandardMaterial;
    唱片: THREE.MeshStandardMaterial;
    地毯白: THREE.MeshStandardMaterial;
    地毯黄: THREE.MeshStandardMaterial;
    身体: THREE.MeshStandardMaterial;
    沙发: THREE.MeshStandardMaterial;
  };
};

export type ActionName = 'move' | 'stand' | '骨架.001动作';
